'use client'

import Link from 'next/link'
import Header from '@/components/Header'

export default function AIDetectorsAreFlawed() {
  return (
    <>
      <Header />

      <main className="min-h-screen bg-white">
        {/* Article Header */}
      <article className="container mx-auto px-4 py-16 max-w-4xl">
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Why AI Detectors Are Fundamentally Flawed
          </h1>
          <p className="text-xl text-gray-600 leading-relaxed">
            A technical analysis of why text classification cannot establish authorship intent,
            and why process-based proof is the only valid method.
          </p>
        </header>

        {/* Introduction */}
        <section className="prose prose-lg max-w-none mb-12">
          <div className="bg-amber-50 border-l-4 border-amber-500 p-6 mb-8">
            <p className="text-lg font-semibold text-gray-900 mb-2">
              Key Insight
            </p>
            <p className="text-gray-800">
              AI detectors attempt to solve an impossible problem: determining the <em>intent</em> behind text
              by analyzing only the text itself. This is logically equivalent to determining if a photograph
              was taken by a human or generated by AI by examining only the pixels.
            </p>
          </div>
        </section>

        {/* Section 1: Authorship ≠ Text Classification */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            1. Authorship ≠ Text Classification
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              AI detectors are trained to classify text as "AI-generated" or "human-written" based on statistical patterns.
              This approach has a fundamental problem: <strong>the same text can be produced by both humans and AI</strong>.
            </p>
            <p>
              Consider these scenarios:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li>A student writes an essay using sophisticated vocabulary and clear structure</li>
              <li>An AI generates the same essay with identical wording</li>
              <li>A student generates text with AI, then rewrites it in their own words</li>
              <li>A student uses AI for brainstorming, then writes independently</li>
            </ul>
            <p>
              <strong>The text itself cannot tell you which scenario occurred.</strong> Authorship is about the <em>process</em>,
              not the output. AI detectors can only analyze the output.
            </p>
          </div>
        </section>

        {/* Section 2: Why Good Writing Looks Like AI */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            2. Why Good Writing Looks Like AI
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              AI language models are trained on vast corpora of human-written text, including:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li>Literary classics and contemporary literature</li>
              <li>Academic papers and journals</li>
              <li>Professional journalism and essays</li>
              <li>Educational materials and textbooks</li>
            </ul>
            <p>
              When AI generates text, it produces patterns that <em>resemble the best examples of human writing</em>
              in its training data. This means:
            </p>
            <div className="bg-red-50 border-l-4 border-red-500 p-6">
              <p className="font-semibold text-gray-900">
                The better you write—with clear structure, varied vocabulary, and logical flow—the more your
                writing will statistically resemble AI-generated text.
              </p>
            </div>
            <p>
              This creates a perverse incentive: students who write <em>worse</em> are less likely to be flagged.
              Students who write <em>better</em> are more likely to be accused.
            </p>
          </div>
        </section>

        {/* Section 3: Why Detectors Cannot Establish Intent */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            3. Why Detectors Cannot Establish Intent
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              Academic integrity violations require proving <strong>intent to deceive</strong>. AI detectors cannot
              establish intent because:
            </p>
            <div className="bg-gray-50 rounded-lg p-6 space-y-4">
              <div>
                <h3 className="font-bold text-gray-900 mb-2">They cannot distinguish legitimate use from cheating</h3>
                <p className="text-gray-700">
                  Using AI for brainstorming, outlining, or editing is often permitted. Detectors cannot tell
                  if AI was used for ideation vs. full text generation.
                </p>
              </div>
              <div>
                <h3 className="font-bold text-gray-900 mb-2">They cannot account for writing assistance tools</h3>
                <p className="text-gray-700">
                  Grammar checkers, spell checkers, and style suggestions all modify text. Many are AI-powered.
                  Detectors flag these legitimate tools as "AI use."
                </p>
              </div>
              <div>
                <h3 className="font-bold text-gray-900 mb-2">They cannot prove causation</h3>
                <p className="text-gray-700">
                  Even if text is statistically similar to AI output, this doesn't prove the student used AI.
                  Correlation is not causation.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Section 4: Why Probabilistic Tools Fail Due Process */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            4. Why Probabilistic Tools Fail Due Process
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              AI detectors output a probability score (e.g., "87% likely AI-generated"). This creates serious
              legal and ethical problems:
            </p>
            <ul className="list-disc ml-6 space-y-3">
              <li>
                <strong>No clear threshold:</strong> Is 50% enough to accuse? 75%? 90%? Different tools use different scales.
              </li>
              <li>
                <strong>High false positive rates:</strong> Studies show 15-30% false positive rates on human-written text,
                especially for non-native English speakers.
              </li>
              <li>
                <strong>Lack of transparency:</strong> Proprietary algorithms with no public validation or peer review.
              </li>
              <li>
                <strong>No right to confront evidence:</strong> Students cannot challenge a black-box algorithm's decision.
              </li>
              <li>
                <strong>Discriminatory impact:</strong> Disproportionately flags non-native speakers, neurodivergent students,
                and students with learning differences.
              </li>
            </ul>
            <div className="bg-red-50 border-l-4 border-red-500 p-6 mt-6">
              <p className="font-semibold text-gray-900">
                Using probabilistic tools to make high-stakes academic decisions violates basic principles of
                due process and creates legal liability for institutions.
              </p>
            </div>
          </div>
        </section>

        {/* Section 5: Why Process-Based Proof Is the Only Valid Method */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            5. Why Process-Based Proof Is the Only Valid Method
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              Instead of trying to classify finished text, we should verify the <em>process</em> of writing.
              This is the only method that can establish authorship with certainty.
            </p>
            <div className="bg-green-50 rounded-lg p-6 space-y-4">
              <div>
                <h3 className="font-bold text-gray-900 mb-2">What process-based proof captures:</h3>
                <ul className="list-disc ml-6 space-y-2 text-gray-700">
                  <li>Every keystroke, deletion, and revision in real-time</li>
                  <li>Typing patterns and behavioral signatures unique to the individual</li>
                  <li>Time spent on different sections and editing patterns</li>
                  <li>The complete evolution from blank page to finished document</li>
                  <li>Collaboration patterns with exact contribution percentages</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-gray-900 mb-2">Why this works:</h3>
                <ul className="list-disc ml-6 space-y-2 text-gray-700">
                  <li><strong>Verifiable:</strong> The writing process can be replayed and audited</li>
                  <li><strong>Tamper-proof:</strong> Cryptographic signatures prevent falsification</li>
                  <li><strong>Transparent:</strong> No black-box algorithms—just observable facts</li>
                  <li><strong>Fair:</strong> Doesn't penalize writing quality or English proficiency</li>
                  <li><strong>Comprehensive:</strong> Shows legitimate AI use (editing, brainstorming) vs. misconduct</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Conclusion */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Conclusion
          </h2>
          <div className="space-y-4 text-gray-700 text-lg leading-relaxed">
            <p>
              AI detectors attempt to solve an unsolvable problem. They:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li>Confuse correlation with causation</li>
              <li>Punish good writing and English proficiency</li>
              <li>Cannot establish intent or distinguish legitimate use</li>
              <li>Violate due process with probabilistic accusations</li>
              <li>Create legal liability for institutions</li>
            </ul>
            <p className="font-semibold text-gray-900 text-xl mt-6">
              Process-based proof is the future of authorship verification.
            </p>
            <p>
              By capturing the complete writing process with cryptographic verification, we can provide
              <em>actual proof</em> of authorship—not just probabilistic guesses. This protects students from
              false accusations and gives institutions defensible evidence of academic integrity.
            </p>
          </div>
        </section>

        {/* CTA Section - Minimal */}
        <section className="border-t border-gray-200 pt-12">
          <div className="bg-gray-50 rounded-lg p-8 text-center">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Here is what real authorship proof looks like.
            </h3>
            <p className="text-gray-700 mb-6 max-w-2xl mx-auto">
              Authorly provides cryptographic, process-based authorship verification—the only valid method
              of proving human authorship in the AI era.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Link
                href="/students"
                className="bg-primary-600 hover:bg-primary-700 text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-200"
              >
                For Students
              </Link>
              <Link
                href="/institutions"
                className="bg-gray-800 hover:bg-gray-900 text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-200"
              >
                For Institutions
              </Link>
            </div>
          </div>
        </section>

        {/* Share/Link Helper */}
        <section className="mt-12 pt-8 border-t border-gray-200">
          <p className="text-sm text-gray-500 text-center">
            Feel free to share this page with colleagues, link to it in academic discussions, or cite it in your work.
            We encourage open dialogue about the limitations of AI detection and the need for better methods.
          </p>
        </section>
      </article>

        {/* Footer */}
        <footer className="border-t border-gray-200 py-8 mt-16">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>&copy; 2025 Authorly. All rights reserved.</p>
          </div>
        </footer>
      </main>
    </>
  )
}
